"""Machines, vehicles, interfaces and signal damage for industrial and science-fiction scenes:
transformers, gearboxes, bearings, a waveguide engine, turbo, tyres, a car passing, interface cues,
glitch and voice effects, statistical textures.

Rendered at the physical engine's rate (48 kHz) and resampled at the boundary, like ``genny.matter``.
The papers and projects it draws on are named below and in ``THIRD_PARTY_NOTICES.md``.

Sources:

* **Transformer** - "Magnetostriction is not linearly proportional to flux density so its waveform
  ... contains a series of even harmonics which span the audible sound spectrum"; noise relates to the
  vibration velocity rather than the peak displacement; compressive stress raises it steeply (Moses,
  Anderson, Phophongviwat & Tabrizi, "Contribution of magnetostriction to transformer noise", UPEC
  2010). On a model core at 1.7 T the displacement spectrum has a pronounced 100 Hz line, significant
  200 and 300 Hz lines and little above; magneto-static forces between laminations add the same
  frequencies and take over where clamping is poor; a DC bias enhances the noise (Shilyashki,
  Pfutzner, Hamberger, Aigner, Kenov & Matkovic, "Spatial distributions of magnetostriction,
  displacements and noise generation of model transformer cores", 2016). Under a DC bias the core
  saturates on one half-cycle only and even harmonics appear in the magnetising current beside the odd
  ones (Hasan, "The effect of DC bias and noise on the performances of power transformer", thesis,
  UniMAP 2014, abstract: only its first 24 pages were read); the strain, even in the flux, then holds
  the odd multiples of f: that step is this module's deduction, not a quoted measurement. That winding
  noise follows the current squared (2f only) is a textbook statement not checked against a source.
  # UNSOURCED: the strain curve, the rattle law, the tank modes.
* **Gear mesh** - f_mesh = z rpm / 60. "The characteristic whine is generated by a constant harmonic
  displacement excitation, caused by errors in the actual tooth position"; the first harmonic of the
  mesh order dominates, and the whine swells where the order crosses structural resonances, measured
  at 920-950, 975-1070 and 1090-1200 Hz on a car (Tosun, Yildiz & Ozkan, "Investigation and refinement
  of gearbox whine noise", Applied Acoustics 130, 2018): hence the default `housing`. The rest is
  Randall, "A new method of modeling gear faults", J. Mechanical Design 104, 1982. Tooth deflection
  under load gives the mesh rate and its harmonics, and is "very load dependent": between under 10 %
  and full load the mesh line rose 21 dB and its second harmonic 7 dB on one gear (Fig. 3). "The
  effects of wear will often be more pronounced at the higher harmonics". An eccentric gear modulates
  the amplitude at its own rotation rate, and "the same fluctuations in tooth contact pressure ...
  result in angular velocity fluctuations at the same frequency": amplitude and frequency modulation
  together, with index beta = (relative speed fluctuation) x (teeth), 1 for a 100-tooth gear at
  +-1 %; their sidebands add on one side and cancel on the other. A fault on one tooth modulates the
  mesh by a pulse one tooth period long (many low sidebands of nearly equal level) and adds an
  impulse (low shaft harmonics). Left out: ghost components (the index wheel of the cutting machine).
  The hunting-tooth rate f_mesh gcd(z1, z2) / (z1 z2) is not in that paper: a textbook statement.
  # UNSOURCED: harmonic roll-off, the 1 % fluctuation at full `eccentricity`, housing mode ratios.
* **Bearing** - Randall & Antoni, "Rolling element bearing diagnostics - a tutorial", MSSP 25, 2011,
  equations 1 to 4 for the four kinematic rates. A defect on a race shocks the structure's resonances
  once per passage; a defect on a ball "strikes the same race" at the ball spin rate, "so that in
  general there are two shocks per basic period". The rates are 1 to 2 % off the kinematic values and
  vary at random by as much, because the balls slip; it is each spacing that is random, not the
  position about a fixed period (their model 2). "Inner race faults would be modulated at shaft
  speed, and rolling element faults at cage speed. For unidirectional load, an outer race fault would
  not be modulated." Left out: the extended spall worn smooth, which gives modulated noise instead of
  impacts (section 2.2), and the constant 1 to 2 % offset of the rates.
  Default geometry is the SKF 6205 of the CWRU bearing data (9 balls, 7.94 mm, pitch 39.04 mm).
  The housing modes, the 7 ms ring, the impact-to-noise level and the character of the outer, ball
  and loose states are fitted to the FSTF sound recordings (Mendeley n9y9c7xrz3: SKF 6004, 600 to
  1800 rpm; comparison in docs/cyber.md). # UNSOURCED: the worn, dry and misaligned recipes.
"""
from __future__ import annotations

import math

import numba
import numpy as np
from scipy import fft as sfft
from scipy.ndimage import uniform_filter1d
from scipy.signal import resample, resample_poly

from . import filters as F
from . import osc as O
from . import spectral as S
from .core import DEFAULT_SR, declick, pad_to, samples, to_mono
from .fx import REGISTRY as FX
from .fx import _per_channel, effect
from .matter import _bp, _fin, _fit, _hp, _lfn, _lp, _n, _rng, _tvbp, _unit
from .physical import modal as M
from .physical.core import SR
from .sfx import _round, sfx


def _modes(x, freqs, decays, gains):
    return M.render_modes(x, M.Modes(freqs, decays, gains, "zeros"))


def _ramp(a: float, b: float, n: int) -> np.ndarray:
    return np.full(n, float(a)) if b is None or b < 0 else np.geomspace(max(a, 1e-3), max(b, 1e-3), n)


def _impacts(n: int, phase: np.ndarray, rng, slip: float = 0.0, width: int = 6, walk: bool = False) -> np.ndarray:
    """One raised-cosine pulse of ``width`` samples each time ``phase`` (in cycles) passes an integer.
    ``slip`` is the standard deviation of the timing error as a fraction of the period: an error about
    a fixed position (gear teeth), or with ``walk`` an error of each spacing, which adds up (rolling
    elements slip and keep no memory of it: Randall & Antoni 2011, section 2.1, model 2)."""
    out = np.zeros(n + width)
    k = np.arange(1, int(phase[-1]) + 1)
    if len(k) == 0:
        return out[:n]
    err = slip * rng.standard_normal(len(k))
    at = np.interp(k + (np.cumsum(err) if walk else err), phase, np.arange(n))
    w = 0.5 - 0.5 * np.cos(2 * np.pi * (np.arange(width) + 0.5) / width)
    for i in at.astype(int):
        out[i:i + width] += w
    return out[:n]


# =============================================================================================
# TRANSFORMER
# =============================================================================================

def magnetostriction(b):
    """Core strain (arbitrary units) for a flux density ``b`` in units of the saturation knee
    (about 1.7 T for grain-oriented steel). Even in ``b``: quadratic below the knee, steeper above.
    # UNSOURCED: the exponential factor stands for the measured butterfly loop's steepening."""
    b = np.asarray(b, float)
    return b * b * np.exp(0.9 * b * b)


@sfx("transformer", "Power transformer / substation hum from the core's magnetostriction: 100 or 120 Hz and its multiples, tank resonances, loose-lamination buzz.",
     dur=(4.0, "s"), mains=(50.0, "Hz supply (50 or 60): the hum is at twice this"),
     flux=(0.8, "0.3..1.3 core induction relative to saturation: higher = more harmonics, harsher"),
     dc_bias=(0.0, "0..0.5 DC magnetisation: brings in the odd multiples (50, 150 Hz), a rougher growl"),
     load=(0.3, "0..1 winding current: adds pure 2f"), loose=(0.0, "0..1 loose laminations / panel: buzz and rattle"),
     size=(1.0, "0.3 small wall unit .. 3 substation: scales the tank resonances down"), seed=(0, "variation"))
def transformer(sr=DEFAULT_SR, dur=4.0, mains=50.0, flux=0.8, dc_bias=0.0, load=0.3, loose=0.0, size=1.0, seed=0):
    """The radiated sound is taken as the strain velocity (a large tank radiates as its surface
    velocity) plus the tank's modes. # UNSOURCED: 0.02 Hz grid wander, 4 % level drift."""
    rng = _rng(seed, 71)
    n = _n(dur)
    f = float(np.clip(mains, 20.0, 400.0))
    wander = 1.0 + 4e-4 * _lfn(rng, n, 0.2)
    th = 2 * np.pi * np.cumsum(f * wander) / SR
    b = float(np.clip(flux, 0.3, 1.3)) * np.sin(th) + float(np.clip(dc_bias, 0.0, 0.5))
    v = np.gradient(magnetostriction(b)) * SR / (2 * np.pi * 2 * f)
    v = v + float(np.clip(load, 0, 1)) * np.sin(2 * th + 0.7)
    lo = float(np.clip(loose, 0.0, 1.0))
    if lo > 0:
        # A loose sheet leaves its neighbour and lands again once per strain cycle.
        gate = np.maximum(np.abs(v) / (np.max(np.abs(v)) + 1e-12) - (1.0 - 0.7 * lo), 0.0) ** 2
        v = v + lo * 6.0 * np.max(np.abs(v)) * _bp(rng.standard_normal(n), 2200.0, 0.8) * gate
    s = float(np.clip(size, 0.3, 3.0))
    tank = np.array([212.0, 318.0, 437.0, 566.0, 801.0]) / s
    y = _unit(v) + 0.5 * _unit(_modes(v, tank, tank * 0.06, [1.0, 0.8, 0.6, 0.45, 0.3]))
    y = y * (1.0 + 0.04 * _lfn(rng, n, 0.3))
    return _fin(_lp(y, 5000.0, 2), sr, 0.5, 0.05, 0.08)


# =============================================================================================
# GEARS
# =============================================================================================

def gear_frequencies(rpm: float, teeth: int, teeth2: int) -> dict:
    """Rates in Hz of a gear pair driven at ``rpm`` on the ``teeth`` side."""
    z1, z2 = max(int(teeth), 1), max(int(teeth2), 1)
    f1 = float(rpm) / 60.0
    mesh = z1 * f1
    return {"shaft_in": f1, "shaft_out": f1 * z1 / z2, "mesh": mesh, "hunting": mesh * math.gcd(z1, z2) / (z1 * z2)}


@sfx("gearbox", "Gear whine: the tooth-mesh tone (teeth x rpm / 60) with shaft-rate sidebands, housing ring and backlash rattle.",
     dur=(3.0, "s"), rpm=(1800.0, "input shaft"), rpm_end=(-1.0, "glide to this rpm (-1 = steady)"),
     teeth=(23, "driving gear"), teeth2=(41, "driven gear"), load=(0.6, "0 idle (rattles) .. 1 loaded (whines)"),
     wear=(0.3, "0 ground and quiet .. 1 worn: more mesh harmonics, a damaged tooth knocking once per turn"),
     eccentricity=(0.3, "0..1 run-out of the shafts: strength of the sidebands (the 'singing' roughness)"),
     backlash=(0.3, "0..1 clearance: rattle when the load is low"), housing=(1050.0, "Hz first casing resonance"),
     seed=(0, "variation"))
def gearbox(sr=DEFAULT_SR, dur=3.0, rpm=1800.0, rpm_end=-1.0, teeth=23, teeth2=41, load=0.6, wear=0.3,
            eccentricity=0.3, backlash=0.3, housing=1050.0, seed=0):
    rng = _rng(seed, 72)
    n = _n(dur)
    z1, z2 = int(np.clip(teeth, 3, 400)), int(np.clip(teeth2, 3, 400))
    f1 = _ramp(float(np.clip(rpm, 10.0, 60000.0)), rpm_end, n) / 60.0
    p1 = np.cumsum(f1) / SR                       # input shaft, turns
    p2 = p1 * z1 / z2
    ecc, w, ld = float(np.clip(eccentricity, 0, 1)), float(np.clip(wear, 0, 1)), float(np.clip(load, 0, 1))
    # Run-out changes the tooth load (amplitude) and the speed of each gear (phase): index
    # beta = fluctuation x teeth (Randall 1982, B3), here 1 % at full `eccentricity`, capped at 1.5 rad.
    beta = lambda z: min(0.01 * ecc * z, 1.5) / (2 * np.pi)
    pm = z1 * p1 + beta(z1) * np.sin(2 * np.pi * p1) + 0.6 * beta(z2) * np.sin(2 * np.pi * p2 + 1.0)
    am = 1.0 + 0.5 * ecc * (np.cos(2 * np.pi * p1) + 0.6 * np.cos(2 * np.pi * p2 + 2.0))
    # One damaged tooth on the driving gear: the mesh swells for one tooth period per turn, and knocks.
    tooth = _impacts(n, p1, rng, width=max(int(SR / (z1 * float(f1.mean()))), 6))
    am = am + 1.5 * w * tooth
    te = np.zeros(n)
    top = 0.4 * SR / (z1 * float(f1.max()))
    for k in range(1, int(min(top, 12)) + 1):
        # Load: 21 dB on the mesh line and 7 dB on its double between 10 % and full load (Randall
        # 1982, Fig. 3). # UNSOURCED: the same law carried on to the higher harmonics.
        te += k ** -(2.2 - 1.4 * w) * max(ld, 0.05) ** (k ** -1.6) * np.sin(2 * np.pi * k * pm + rng.uniform(0, 6.28))
    exc = te * am
    exc += w * 4.0 * _impacts(n, p1, rng)
    bl = float(np.clip(backlash, 0, 1)) * (1.0 - ld)
    if bl > 0:
        hits = _impacts(n, z1 * p1, rng, slip=0.25)
        exc += bl * 3.0 * hits * (rng.random(n) < 0.5) * (0.5 + 0.5 * np.cos(2 * np.pi * p1))
    h = float(np.clip(housing, 200.0, 8000.0)) * np.array([1.0, 1.42, 2.05, 2.9])
    y = 0.5 * _unit(exc) + _unit(_modes(exc, h, h * 0.02, [1.0, 0.6, 0.4, 0.25]))
    return _fin(_lp(_hp(y, 60.0), 9000.0, 2), sr, 0.5, 0.01, 0.03)


# =============================================================================================
# BEARINGS
# =============================================================================================

def bearing_frequencies(rpm: float, balls: int = 9, ball_mm: float = 7.94, pitch_mm: float = 39.04,
                        angle_deg: float = 0.0) -> dict:
    """Kinematic rates in Hz for a fixed outer race: ball pass outer / inner, ball spin, cage (FTF)."""
    fr = float(rpm) / 60.0
    r = ball_mm / pitch_mm * math.cos(math.radians(angle_deg))
    return {"shaft": fr, "bpfo": balls / 2.0 * fr * (1.0 - r), "bpfi": balls / 2.0 * fr * (1.0 + r),
            "bsf": pitch_mm / (2.0 * ball_mm) * fr * (1.0 - r * r), "ftf": fr / 2.0 * (1.0 - r)}


BEARING_STATES = ("healthy", "worn", "dry", "outer", "inner", "ball", "loose", "misaligned")


@sfx("bearing", "Rolling bearing on a spinning shaft, healthy or failing: rumble, dry squeal, the periodic ticking of a race or ball defect, a loose or misaligned shaft.",
     dur=(3.0, "s"), rpm=(1750.0, "shaft"), rpm_end=(-1.0, "glide to this rpm (-1 = steady)"),
     state=("healthy", "|".join(BEARING_STATES)), severity=(0.6, "0..1 how far gone"),
     balls=(9, "rolling elements"), ball_mm=(7.94, "ball diameter"), pitch_mm=(39.04, "pitch diameter"),
     resonance=(1000.0, "Hz main housing resonance (others at 0.7, 2 and 4.1 times it)"), seed=(0, "variation"))
def bearing(sr=DEFAULT_SR, dur=3.0, rpm=1750.0, rpm_end=-1.0, state="healthy", severity=0.6, balls=9, ball_mm=7.94,
            pitch_mm=39.04, resonance=1000.0, seed=0):
    if state not in BEARING_STATES:
        raise ValueError(f"bearing state {state!r}: use one of {', '.join(BEARING_STATES)}")
    rng = _rng(seed, 73)
    n = _n(dur)
    sv = float(np.clip(severity, 0.0, 1.0))
    fr = _ramp(float(np.clip(rpm, 10.0, 60000.0)), rpm_end, n) / 60.0
    k = bearing_frequencies(60.0, int(np.clip(balls, 3, 60)), float(ball_mm), float(pitch_mm))   # per shaft turn
    turns = np.cumsum(fr) / SR
    shaft, cage = 2 * np.pi * turns, 2 * np.pi * turns * k["ftf"]
    speed = np.sqrt(fr / float(fr.max()))
    # Housing: four modes at 0.7, 1, 2 and 4.1 times `resonance`, ringing about 7 ms. With the default
    # these are the 700 Hz, 1 kHz, 2 kHz and 4.1 kHz peaks of the FSTF recordings of an SKF 6004.
    f0 = float(np.clip(resonance, 200.0, 8000.0))
    res = f0 * np.array([0.7, 1.0, 2.0, 4.1])
    housing = lambda force: _modes(force, res, np.array([120.0, 140.0, 180.0, 260.0]), [0.7, 1.0, 1.0, 0.3])
    # Rolling noise: surface roughness under the balls ringing the housing, over the low-mid rumble of
    # the shaft and frame; each ball passing the load modulates it slightly.
    roll = _unit(housing(rng.standard_normal(n))) + 0.5 * _unit(_lp(_hp(rng.standard_normal(n), 150.0), 900.0, 2))
    roll = _unit(roll) * (1.0 + 0.03 * np.cos(shaft * k["bpfo"]))
    y = roll * speed + 0.15 * np.sin(shaft)
    force, level = np.zeros(n), 1.0
    if state == "worn":
        y += sv * (0.9 * roll * speed * (1.0 + 0.5 * _lfn(rng, n, 30.0)) + 0.6 * _unit(_lp(rng.standard_normal(n), 300.0)))
        force = (rng.random(n) < sv * 40.0 * fr / SR) * rng.exponential(1.0, n)
    elif state == "dry":
        # Unlubricated cage and balls stick and slip: a narrow squeal that breaks up once per turn.
        sq = _bp(rng.standard_normal(n), f0 * 2.6, 60.0) * np.clip(0.6 + 0.6 * np.sin(shaft) + 0.5 * _lfn(rng, n, 12.0), 0.0, None)
        y += sv * 2.5 * _unit(sq)
    elif state == "outer":
        # A fixed defect in the load zone: every ball hits it alike, so it is a steady, soft ticking.
        force, level = _impacts(n, turns * k["bpfo"], rng, slip=0.02, width=24, walk=True), 0.45
    elif state == "inner":
        force, level = _impacts(n, turns * k["bpfi"], rng, slip=0.01, walk=True) * np.maximum(np.cos(shaft), 0.0) ** 2, 1.4
    elif state == "ball":
        # The damaged ball strikes a race twice per spin, but only inside the load zone, where the cage
        # brings it once per turn, and while its defect faces a race. Slip is 3 % per strike, above the
        # tutorial's 1 to 2 %: the FSTF ball recordings show no line at the strike rate, only the cage
        # rate and its multiples, and that much slip is what smears it.
        gate = np.clip(_lfn(rng, n, float(fr.mean()) * k["ftf"]) + 0.3, 0.0, 1.0)
        force, level = _impacts(n, turns * 2.0 * k["bsf"], rng, slip=0.03, width=12, walk=True) * np.maximum(np.cos(cage), 0.0) ** 2 * gate, 0.5
        y *= 1.0 + 0.25 * sv * np.cos(cage)
    elif state == "loose":
        # Clearance lets the shaft orbit: a low rumble that swells every turn and every other turn.
        rumble = _unit(_lp(_hp(rng.standard_normal(n), 250.0), 900.0, 2)) * (1.0 + 0.6 * np.cos(shaft) + 0.3 * np.cos(shaft / 2.0))
        y += sv * (2.5 * rumble + 0.3 * (np.sin(shaft) + 0.5 * np.sin(2 * shaft) + 0.4 * np.sin(0.5 * shaft)))
    elif state == "misaligned":
        y += sv * (0.8 * np.sin(2 * shaft) + 0.3 * np.sin(shaft) + 0.5 * roll * speed * np.cos(2 * shaft))
    if force.any():
        # Impact level against the rolling noise: about equal at severity 0.6 (FSTF), 14 dB over at 1.
        y += level * 5.0 * sv ** 3 * math.sqrt(float(np.mean(y * y))) * _unit(housing(force * speed))
    return _fin(_lp(_hp(y, 25.0), 6000.0, 2), sr, 0.5, 0.01, 0.03)


# =============================================================================================
# ENGINE AS WAVEGUIDES, TURBO, TYRES, PASS-BY
# =============================================================================================
# Baldan, Lachambre, Delle Monache & Boussard, "Physically informed car engine sound synthesis for
# virtual and augmented environments" (SIVE 2015), as implemented by Antonio-R1/engine-sound-generator
# and DasEtwas/enginesound: over one 720 degree cycle x in [0, 1) each cylinder has
#   intake valve   sin(4 pi x)              on 0    < x < 0.25
#   exhaust valve  -sin(4 pi x)             on 0.75 < x < 1
#   piston         cos(4 pi x)
#   ignition       sin(2 pi (x - 0.5) / t)  on 0.5  < x < 0.5 + t / 2
# and feeds an intake and an exhaust waveguide whose reflection at the cylinder end follows the valve:
# r = r_open v + r_closed (1 - v). The exhausts join in a collector, a straight pipe and a muffler
# of four short parallel guides. Constants are DasEtwas' default.esc unless marked.
# Left out of the paper's model: the cylinder itself as a waveguide whose length follows the piston
# (cylinder volume and compression ratio), and the outlet pipe after the muffler. Backfire is the
# paper's: while the engine revs down, each cycle fires an ignition-shaped pulse into the exhaust
# with a probability that is multiplied by itself after every pop.

@numba.njit(cache=True)
def _pipe_engine_k(inc, offs, noise, pops, n_ex, n_in, n_pipe, n_muf, pf, igf, ign_t):
    n, C = len(inc), len(offs)
    exu, exl = np.zeros((C, n_ex.max())), np.zeros((C, n_ex.max()))
    inu, inl = np.zeros((C, n_in)), np.zeros((C, n_in))
    pu, pl = np.zeros(n_pipe), np.zeros(n_pipe)
    mu, ml = np.zeros((4, n_muf.max())), np.zeros((4, n_muf.max()))
    out = np.zeros((3, n))                                   # intake, exhaust, block vibration
    x = 0.0
    back = 0.0                                               # wave returning from the pipe into the headers
    for t in range(n):
        x = (x + inc[t]) % 1.0
        coll, intake, vib = 0.0, 0.0, 0.0
        for c in range(C):
            xc = (x + offs[c]) % 1.0
            iv = math.sin(4 * math.pi * xc) if xc < 0.25 else 0.0
            ev = -math.sin(4 * math.pi * xc) if xc > 0.75 else 0.0
            cyl = pf * math.cos(4 * math.pi * xc)
            if 0.5 < xc < 0.5 + ign_t / 2:
                cyl += igf * math.sin(2 * math.pi * (xc - 0.5) / ign_t)
            vib += cyl
            # exhaust guide: left end = valve, right end = collector
            i = t % n_ex[c]
            r = 0.01 * ev + 0.7145 * (1.0 - ev)
            u, lo = exu[c, i], exl[c, i]
            exu[c, i] = (1.0 - r) * cyl * 0.5 + r * lo
            exl[c, i] = back / C + 0.06 * u
            coll += u * 0.94
            # intake guide: left end = open air (inverting), right end = valve
            i = t % n_in
            r = 0.006 * iv + 1.0 * (1.0 - iv)
            u, lo = inu[c, i], inl[c, i]
            inu[c, i] = -0.7576 * lo
            inl[c, i] = (1.0 - r) * cyl * 0.5 + noise[t] * iv + r * u
            intake += lo * 1.7576
        i = t % n_pipe
        u, lo = pu[i], pl[i]
        pu[i] = coll / C + pops[t] + 0.0617 * lo
        back = lo * (1.0 - 0.0617)
        ret, ex = 0.0, 0.0
        for j in range(4):
            k = t % n_muf[j]
            a, b = mu[j, k], ml[j, k]
            mu[j, k] = u * 0.25
            ml[j, k] = -0.142 * a
            ex += a * 1.142
            ret += b
        pl[i] = ret
        out[0, t], out[1, t], out[2, t] = intake, ex, vib
    return out


@sfx("pipe_engine", "Four-stroke engine built from its plumbing: each cylinder's valves gate an intake and an exhaust waveguide, joined by a collector, a pipe and a muffler. Rasps, drones and lopes like a real exhaust.",
     dur=(3.0, "s"), rpm=(1800.0, "crankshaft"), rpm_end=(-1.0, "glide to this rpm (-1 = steady)"), cylinders=(4, "1..12"),
     load=(0.5, "0 coasting .. 1 full throttle: combustion strength and intake roar"),
     header=(1.6, "ms exhaust runner length per cylinder: short = raspy, long = deep"),
     pipe=(6.0, "ms straight pipe before the muffler (the drone)"),
     lope=(0.0, "0 even firing .. 1 uneven (odd cylinders fire early: V-twin / cammed idle)"),
     unequal=(0.15, "0..0.5 spread of the header lengths (unequal headers burble)"),
     mic=(0.3, "0 at the tailpipe .. 1 at the air intake"),
     backfire=(0.0, "0..0.99 chance of a pop in the exhaust per engine cycle, only while the rpm falls (rpm_end below rpm); each pop makes the next less likely"),
     seed=(0, "variation"))
def pipe_engine(sr=DEFAULT_SR, dur=3.0, rpm=1800.0, rpm_end=-1.0, cylinders=4, load=0.5, header=1.6, pipe=6.0,
                lope=0.0, unequal=0.15, mic=0.3, backfire=0.0, seed=0):
    """`lope` is the paper's "cycle asymmetry". # UNSOURCED: its law and the unequal-header law (DasEtwas
    stores one offset and one length per cylinder; these two knobs generate them), the pop level,
    the 1 % crank-speed flutter, and the ignition time
    going from DasEtwas' 0.069 of a cycle at no load to Antonio-R1's 0.016 at full load."""
    rng = _rng(seed, 75)
    n = _n(dur)
    C = int(np.clip(cylinders, 1, 12))
    ld = float(np.clip(load, 0.0, 1.0))
    inc = _ramp(float(np.clip(rpm, 200.0, 20000.0)), rpm_end, n) / (120.0 * SR) * (1.0 + 0.01 * _lfn(rng, n, 57.0))
    offs = (np.arange(C) / C - (np.arange(C) % 2) * 0.5 * float(np.clip(lope, 0, 1)) / C) % 1.0
    spread = 1.0 + float(np.clip(unequal, 0, 0.5)) * np.linspace(-1.0, 1.0, C) if C > 1 else np.ones(1)
    n_ex = np.maximum((float(np.clip(header, 0.3, 12.0)) * 1e-3 * SR * spread).astype(np.int64), 4)
    n_muf = np.array([7, 9, 10, 12], dtype=np.int64)        # 0.146 / 0.1875 / 0.208 / 0.25 ms
    noise = 0.181 * ld * _lp(rng.uniform(-1, 1, n), 10900.0)
    n_pipe = max(int(float(np.clip(pipe, 0.5, 40.0)) * 1e-3 * SR), 4)
    ign_t = 0.069 - 0.053 * ld
    pops = np.zeros(n)
    prob = float(np.clip(backfire, 0.0, 0.99))
    if prob > 0 and 0 <= rpm_end < rpm:
        cyc = np.cumsum(inc)
        for start in np.searchsorted(cyc, np.arange(1, int(cyc[-1]) + 1)):
            if rng.random() < prob:
                m = max(int(0.5 * ign_t / inc[min(start, n - 1)]), 4)
                seg = 2.5 * np.sin(np.pi * np.arange(m) / m)
                pops[start:start + m] += seg[:max(n - start, 0)]
                prob *= prob
    o = _pipe_engine_k(np.ascontiguousarray(inc), offs, noise, pops, n_ex, 9, n_pipe, n_muf, 2.43, 2.0 + 6.0 * ld, ign_t)
    m = float(np.clip(mic, 0.0, 1.0))
    y = (1.0 - m) * 0.639 * o[1] + m * 0.325 * o[0] + 0.036 * _lp(o[2], 92.0)
    return _fin(_hp(y, 25.0), sr, 0.6, 0.01, 0.03)


@sfx("turbo", "Turbocharger: the compressor whine rising as it spools, intake hiss, and the blow-off valve when the throttle shuts.",
     dur=(2.5, "s"), spool=(90000.0, "peak shaft rpm, 30000..200000 (the pitch of the whine)"), boost=(0.7, "0..1 how hard it is pushed: hiss and blow-off level"),
     blowoff=(1, "1 = end on the blow-off valve's pshh"), flutter=(0.0, "0..1 compressor surge chatter in the blow-off"), seed=(0, "variation"))
def turbo(sr=DEFAULT_SR, dur=2.5, spool=90000.0, boost=0.7, blowoff=1, flutter=0.0, seed=0):
    """Agent00PED/ice-simulator, audio/mechsynth.js: whine a^2 (0.22 sin p + 0.1 sin 2p + 0.05 a sin 7p)
    (0.4 + 6 mdot) with a = min(1, w / 9000 rad/s); hiss band-passed at 3000 + 0.35 w Hz; blow-off
    band-passed at 1400 + 5500 boost Hz, Q 0.7. # UNSOURCED: the spool curve, the mass flow scale
    (0.1 at full boost) and the flutter rate."""
    rng = _rng(seed, 76)
    n = _n(dur)
    b = float(np.clip(boost, 0.0, 1.0))
    t = np.arange(n) / SR
    rel = 0.72 * n / SR if blowoff else 10.0 * n / SR
    up = 1.0 - np.exp(-t / (0.22 * n / SR))
    w = float(np.clip(spool, 3e4, 2e5)) * 2 * np.pi / 60.0 * np.where(t < rel, up, up * np.exp(-(t - rel) / 0.5))
    mdot = 0.1 * b * np.where(t < rel, up, 0.0)
    a = np.minimum(1.0, w / 9000.0)
    ph = np.cumsum(w) / SR
    y = a * a * (0.22 * np.sin(ph) + 0.1 * np.sin(2 * ph) + 0.05 * a * np.sin(7 * ph)) * (0.4 + 6.0 * mdot)
    y = y + 2.0 * _tvbp(rng.standard_normal(n), 3000.0 + 0.35 * w, 1.5) * mdot * a
    if blowoff:
        k = int(rel * SR)
        m = np.arange(n - k)
        env = np.exp(-m / (0.18 * SR)) * (1.0 - np.exp(-m / (0.004 * SR)))
        env = env * (1.0 + 0.9 * float(np.clip(flutter, 0, 1)) * np.sign(np.sin(2 * np.pi * 38.0 * m / SR)))
        y[k:] += 1.2 * b * _bp(rng.standard_normal(n - k), 1400.0 + 5500.0 * b, 0.7) * env
    return _fin(_lp(y, 5500.0, 2), sr, 0.5, 0.01, 0.02)


@sfx("tyre_squeal", "Tyres scrubbing past their grip limit (a drift, a hard brake, a getaway).",
     dur=(1.5, "s"), slip=(0.8, "0.2 chirp .. 1.5 full slide: pitch and harshness"), wobble=(0.5, "0..1 unsteadiness of the slide"), seed=(0, "variation"))
def tyre_squeal(sr=DEFAULT_SR, dur=1.5, slip=0.8, wobble=0.5, seed=0):
    """Agent00PED/ice-simulator, audio/mechsynth.js: per wheel, noise through a band-pass at
    900 + 700 s + 220 i Hz with Q 2.2 + 1.5 env. # UNSOURCED: Q scaled by 6 for an offline render
    (theirs is a state-variable filter driven hard), the slip wander."""
    rng = _rng(seed, 77)
    n = _n(dur)
    y = np.zeros(n)
    s0 = float(np.clip(slip, 0.05, 1.5))
    for i in range(4):
        s = np.clip(s0 * (1.0 + 0.35 * float(np.clip(wobble, 0, 1)) * _lfn(rng, n, 5.0)), 0.05, 1.5)
        env = np.clip(s / s0, 0.0, 1.5) / 1.5
        y += _tvbp(rng.standard_normal(n), 900.0 + 700.0 * s + 220.0 * i, 6.0 * (2.2 + 1.5 * env)) * env
    return _fin(y, sr, 0.5, 0.02, 0.08)


# Harmonoise source model, category 1 (cars), third-octave bands 20 Hz .. 12.5 kHz: Jonasson et al.,
# "Source modelling of road vehicles", SP Swedish National Testing and Research Institute, 2004.
# Rolling L = aR + bR log10(v / 70 km/h); propulsion L = aP + bP (v - 70) / 70.
_HN_F = 20.0 * 2.0 ** (np.arange(29) / 3.0)
_HN_AR = np.array([69.9, 69.9, 69.9, 74.9, 74.9, 74.9, 79.3, 82.5, 81.3, 80.9, 78.9, 78.8, 80.5, 85.7, 87.7, 89.2, 90.6,
                   89.9, 89.4, 87.6, 85.6, 82.5, 79.6, 76.8, 74.5, 71.9, 69.0, 69.0, 69.0])
_HN_BR = np.array([33.0, 33.0, 33.0, 30.0, 30.0, 30.0, 41.0, 41.2, 42.3, 41.8, 38.6, 35.5, 31.7, 21.5, 21.2, 23.5, 29.1,
                   33.5, 34.1, 35.1, 36.4, 37.4, 38.9, 39.7, 39.7, 39.7, 39.7, 39.7, 39.7])
_HN_AP = np.array([85.8, 87.6, 97.5, 87.5, 96.6, 97.2, 91.5, 86.7, 86.8, 84.9, 86.0, 86.0, 85.9, 80.6, 80.2, 77.8, 78.0,
                   81.4, 82.3, 82.6, 81.5, 80.7, 78.8, 77.0, 76.0, 74.0, 72.0, 72.0, 72.0])
_HN_BP = np.where(_HN_F < 195.0, 0.0, 8.2)


def road_noise_levels(kmh: float) -> tuple[np.ndarray, np.ndarray]:
    """(rolling, propulsion) sound power levels in dB per third-octave band of ``_HN_F``."""
    v = max(float(kmh), 1.0)
    return _HN_AR + _HN_BR * np.log10(v / 70.0), _HN_AP + _HN_BP * (v - 70.0) / 70.0


def _third_octave_noise(n: int, rng, levels_db: np.ndarray) -> np.ndarray:
    """Noise with the given third-octave band levels: a band of constant level has a power density
    falling as 1 / f, so the spectrum is shaped by the interpolated level minus 10 log10 f."""
    f = np.maximum(np.fft.rfftfreq(n, 1.0 / SR), 1.0)
    g = np.interp(np.log(f), np.log(_HN_F), levels_db, left=levels_db[0] - 30.0, right=levels_db[-1] - 30.0)
    return np.fft.irfft(np.fft.rfft(rng.standard_normal(n)) * 10 ** ((g - 10 * np.log10(f)) / 20.0), n)


@sfx("pass_by", "A car driving past: tyre roar that grows with speed, engine or electric drive, wind, the Doppler drop and the ground reflection.",
     dur=(5.0, "s"), speed=(60.0, "km/h, 10..250"), distance=(6.0, "m from the lane at the closest point"),
     power=("combustion", "combustion | electric | none (tyres and wind only)"), cylinders=(4, "combustion: cylinder count"),
     gear=(3.2, "combustion: engine rpm = gear x 26 x km/h (2.2 top gear .. 6 low gear)"),
     wet=(0.0, "0 dry .. 1 wet road: spray hiss above 2 kHz"), direction=("lr", "lr | rl"),
     pan=(1, "1 = stereo, panned across; 0 = mono (when the game positions it itself)"), seed=(0, "variation"))
def pass_by(sr=DEFAULT_SR, dur=5.0, speed=60.0, distance=6.0, power="combustion", cylinders=4, gear=3.2, wet=0.0,
            direction="lr", pan=1, seed=0):
    """Source = Harmonoise rolling noise + a propulsion source scaled to the Harmonoise propulsion
    energy (the calibration of Damiano, Bondi, Guntoro & van Waterschoot, "A framework for the acoustic
    simulation of passing vehicles using variable length delay lines", EURASIP J. Audio Speech Music
    Process. 2024:49, and of boschresearch/acoustic-traffic-simulation-counting) + aerodynamic noise (ice-simulator
    audio/wind.js: pink noise low-passed at 250 + 30 v Hz, level (v / 40)^2.5, v in m/s).
    Propagation = the ``doppler`` effect with its ground path.
    # UNSOURCED: the wet-road spray; the electric drive (a 9:1 reduction gear, 0.33 m wheels and
    # the ripple tone of a 4-pole-pair motor on a six-step inverter), 12 dB under a combustion engine."""
    from .reverbs import doppler
    if power not in ("combustion", "electric", "none"):
        raise ValueError(f"pass_by power {power!r}: use combustion, electric or none")
    rng = _rng(seed, 78)
    kmh = float(np.clip(speed, 10.0, 250.0))
    v = kmh / 3.6
    n = _n(dur)
    lr, lp = road_noise_levels(kmh)
    y = _unit(_third_octave_noise(n, rng, lr))
    if wet > 0:
        y = y + float(np.clip(wet, 0, 1)) * 0.8 * _unit(_hp(rng.standard_normal(n), 2000.0, 2))
    if power == "combustion":
        eng = pipe_engine(sr=SR, dur=n / SR, rpm=float(np.clip(kmh * 26.0 * float(gear), 700.0, 9000.0)), cylinders=cylinders, seed=seed)
    elif power == "electric":
        mrpm = v / (2 * math.pi * 0.33) * 60.0 * 9.0
        eng = gearbox(sr=SR, dur=n / SR, rpm=mrpm, teeth=17, teeth2=153, load=0.8, wear=0.05, eccentricity=0.15,
                      backlash=0.0, housing=2600.0, seed=seed)
        eng = eng + 0.3 * np.sin(2 * np.pi * min(mrpm / 60.0 * 24.0, 9000.0) * np.arange(len(eng)) / SR)
    if power != "none":
        ratio = float(np.sum(10 ** (lp / 10)) / np.sum(10 ** (lr / 10)))
        y = y + math.sqrt(ratio) * (0.25 if power == "electric" else 1.0) * _unit(_fit(eng, n))
    y = y + 1.5 * (v / 40.0) ** 2.5 * _unit(_lp(O.pink(n, int(seed) + 78), 250.0 + 30.0 * v))
    y = doppler(_fin(y, SR, 0.9, 0.3, 0.3), SR, speed=v, closest=float(np.clip(distance, 1.0, 200.0)), direction=direction,
                pan=bool(pan), ground=0.35)
    if int(sr) != SR:
        g = math.gcd(int(sr), SR)
        y = resample_poly(y, int(sr) // g, SR // g, axis=0)
    return y * (0.7 / (float(np.max(np.abs(y))) + 1e-12))


# =============================================================================================
# INTERFACE SOUNDS
# =============================================================================================
# The layer grammar and the note / timing ranges are those of m1ckc3s/procedural-sounds
# (lib/audio/synth.ts, compose.ts): a layer is an oscillator with an optional glide and 2:1 FM, a
# linear attack and an exponential fall of time constant decay / 3; success figures rise by consonant
# intervals, error figures fall or repeat low, warnings repeat a pitch. Its ear-safety limits
# (data/pool/limits.json) are kept: square and saw layers are rounded by a low-pass.
# The ten cyberpunk figures themselves are # UNSOURCED arrangements of that grammar.

UI_KINDS = ("scan", "confirm", "deny", "hack", "decrypt", "upload", "warning", "target_lock", "implant", "neural_link")
_PENTA = np.array([0, 3, 5, 7, 10, 12, 15, 17, 19, 22, 24])


def _st(semitones) -> float:
    return 2.0 ** (np.asarray(semitones, float) / 12.0)


def _tone(sr, f0, decay, wave="sine", f1=None, attack=0.003, fm=0.0):
    n = samples(attack + decay, sr)
    f = np.geomspace(f0, f1 or f0, n)
    if wave == "sine":
        x = O.fm(f, n, sr, 2.0, fm / (2.0 * f0)) if fm else O.sine(f, n, sr)
    else:
        x = _round(O.osc(wave, f, n, sr), f, sr) * 0.6
    t = np.arange(n) / sr
    return x * np.minimum(t / attack, 1.0) * np.exp(-np.maximum(t - attack, 0.0) * 3.0 / decay)


def _swish(sr, dur, lo, hi, q, seed):
    n = samples(dur, sr)
    return F.lowpass(F.biquad(O.white(n, seed=seed), "bandpass", np.geomspace(lo, hi, n), sr, q=q), 3500.0, sr, order=2) * np.hanning(n)


@sfx("cyber_ui", "Sci-fi interface cue: scan, confirm, deny, hack, decrypt, upload, warning, target_lock, implant or neural_link. Every seed is another cue of the same family.",
     kind=("confirm", "|".join(UI_KINDS)), pitch=(1.0, "0.5..2 transposes the whole cue"), seed=(0, "variation"))
def cyber_ui(sr=DEFAULT_SR, kind="confirm", pitch=1.0, seed=0):
    if kind not in UI_KINDS:
        raise ValueError(f"cyber_ui kind {kind!r}: use one of {', '.join(UI_KINDS)}")
    rng = np.random.default_rng([abs(int(seed)), 74, UI_KINDS.index(kind)])
    u, p, s = rng.uniform, float(np.clip(pitch, 0.25, 4.0)), int(seed)
    ev = []                                                  # (start s, signal, gain)
    crush = False
    if kind == "scan":
        d = u(0.28, 0.4)
        lo = u(600, 900) * p
        ev.append((0.0, _swish(sr, d, lo, lo * u(4, 7), 3.0, s), 1.0))
        beep = _tone(sr, u(900, 1300) * p, d, "square", attack=0.005)
        ev.append((0.0, beep * (np.sin(2 * np.pi * u(18, 30) * np.arange(len(beep)) / sr) > 0), 0.12))
    elif kind == "confirm":
        f, gap = u(350, 600) * p, u(0.07, 0.14)
        for i, semi in enumerate((0, 7, 12)):
            ev.append((i * gap, _tone(sr, f * _st(semi), 0.3 if i == 2 else 0.12, fm=u(100, 300)), 0.22))
    elif kind == "deny":
        f, gap = u(180, 320) * p, u(0.05, 0.08)
        for i in range(3):
            ev.append((i * gap, _tone(sr, f, u(0.03, 0.05), "square"), 0.3))
        ev.append((0.0, _tone(sr, f * _st(1), 3 * gap, "triangle"), 0.1))          # dissonant pair
    elif kind in ("hack", "decrypt"):
        f, gap, t, crush = u(400, 600) * p, 1.0 / u(20, 40), 0.0, True
        for i in range(int(rng.integers(10, 17))):
            if rng.random() > 0.1:
                ev.append((t, _tone(sr, f * _st(rng.choice(_PENTA)), u(0.015, 0.04), "square", attack=0.001), 0.22))
            t += gap
            gap *= 1.15 if kind == "decrypt" else 1.0
        if kind == "decrypt":
            ev.append((t, _tone(sr, f * _st(12), 0.35, fm=120.0), 0.3))
    elif kind == "upload":
        f, gap, step = u(350, 500) * p, u(0.04, 0.07), rng.choice([3, 4, 5])
        k = int(rng.integers(6, 9))
        ev.append((0.0, _swish(sr, k * gap + 0.1, 300 * p, 2400 * p, 1.2, s), 0.5))
        for i in range(k):
            ev.append((i * gap, _tone(sr, f * _st(step * i), 0.06, "triangle"), 0.22))
    elif kind == "warning":
        f, gap = u(400, 600) * p, u(0.09, 0.13)
        for rep in range(2):
            for i, semi in enumerate((rng.choice([3, 4]), 0)):
                ev.append((rep * 2.6 * gap + i * gap, _tone(sr, f * _st(semi), 0.1, "square"), 0.25))
    elif kind == "target_lock":
        f, gap, t = u(700, 1000) * p, u(0.13, 0.17), 0.0
        for _ in range(6):
            ev.append((t, _tone(sr, f, 0.02, attack=0.001), 0.25))
            t += gap
            gap *= 0.7
        hold = _tone(sr, u(1200, 1500) * p, 0.6)
        ev.append((t, hold[:samples(0.17, sr)], 0.3))
    elif kind == "implant":
        ev.append((0.0, F.bandpass(O.white(samples(0.03, sr), seed=s), u(800, 2500), sr, 1.5) * np.hanning(samples(0.03, sr)), 1.2))
        f = u(60, 120)
        ev.append((0.0, _tone(sr, f, 0.2, f1=f / 2), 0.6))
        ev.append((0.012, _tone(sr, u(1600, 2400) * p, 0.09, fm=u(200, 350)), 0.1))
    else:                                                    # neural_link: a detuned pair blooming
        f = u(300, 480) * p
        cents = u(5, 14)
        for g, r in ((0.2, 1.0), (0.12, 1.5)):
            for det in (-cents, cents):
                ev.append((0.0, _tone(sr, f * r * _st(det / 100.0), 0.6, attack=u(0.03, 0.09)), g))
        ev.append((0.0, _tone(sr, f + 40.0, 0.6, attack=0.2), 0.08))                # the same tone shifted 40 Hz
        ev.append((0.0, _swish(sr, 0.5, 500 * p, 3000 * p, 2.0, s), 0.25))
    y = np.zeros(max(int(t0 * sr) + len(x) for t0, x, _ in ev) + 8)
    for t0, x, g in ev:
        i = int(t0 * sr)
        y[i:i + len(x)] += g * x
    if crush:
        y = FX["bitcrush"]["fn"](y, sr, bits=6, rate=11025)
        y = F.lowpass(y, 4000.0, sr, order=2)
    return declick(y * (0.6 / (np.max(np.abs(y)) + 1e-12)), sr, 4.0)


# =============================================================================================
# GLITCH AND VOICE EFFECTS
# =============================================================================================

def _edge(L: int, ramp: int, ndim: int) -> np.ndarray:
    w = np.ones(L)
    if ramp > 0:
        w[:ramp] = np.linspace(0.0, 1.0, ramp)
        w[-ramp:] = w[:ramp][::-1]
    return w[:, None] if ndim == 2 else w


@effect("packet_loss", "Lossy digital link: packets drop out in bursts and are muted, replaced by the last good one fading away, or by its frozen spectrum (bad radio, failing implant, VoIP).",
        loss=(0.1, "fraction of packets lost, 0..0.95"), burst=(2.0, "average number of packets lost in a row (1 = scattered)"),
        packet_ms=(20.0, "packet length, 10..60 ms"), conceal=("repeat", "mute | repeat (stutter) | noise (the last spectrum with random phase)"),
        seed=(0, "which packets"))
def packet_loss(x, sr=DEFAULT_SR, loss=0.1, burst=2.0, packet_ms=20.0, conceal="repeat", seed=0):
    """Gilbert two-state channel: P(bad -> good) = 1 / burst, P(good -> bad) chosen so the long-run
    loss is ``loss``. Concealment as in a waveform-substitution decoder: each lost packet is the
    previous output packet at 0.7 of its level. # UNSOURCED: the 0.7 and the 1 ms edges."""
    if conceal not in ("mute", "repeat", "noise"):
        raise ValueError(f"packet_loss conceal {conceal!r}: use mute, repeat or noise")
    rng = np.random.default_rng(int(seed))
    y = np.array(x, dtype=np.float64)
    L = max(16, int(float(np.clip(packet_ms, 2.0, 500.0)) * 1e-3 * sr))
    p, r = float(np.clip(loss, 0.0, 0.95)), 1.0 / max(float(burst), 1.0)
    g = min(1.0, p * r / (1.0 - p))
    w = _edge(L, min(L // 4, int(0.001 * sr)), y.ndim)
    bad = False
    for i in range(L, len(y) - L + 1, L):
        bad = rng.random() < ((1.0 - r) if bad else g)
        if not bad:
            continue
        if conceal == "mute":
            y[i:i + L] = 0.0
        elif conceal == "repeat":
            y[i:i + L] = 0.7 * y[i - L:i] * w
        else:
            S = np.abs(np.fft.rfft(y[i - L:i], axis=0))
            y[i:i + L] = 0.7 * np.fft.irfft(S * np.exp(1j * rng.uniform(0, 2 * np.pi, S.shape)), L, axis=0) * w
    return y


@effect("beat_repeat", "Buffer repeat: now and then a slice of the sound is caught and played again in place of what follows (stutter, roll, reverse), without changing the length.",
        grid=(0.125, "slice length in seconds (at 120 bpm: 0.125 = a 16th note)"), chance=(0.3, "probability that a slice is caught"),
        repeats=(3, "times the caught slice is played"), divide=(1, "play only the first 1/divide of the slice, that many times (2, 4, 8 = rolls)"),
        decay=(0.85, "level of each repeat relative to the one before"), reverse=(0.2, "probability that a caught slice plays backwards"),
        seed=(0, "which slices"))
def beat_repeat(x, sr=DEFAULT_SR, grid=0.125, chance=0.3, repeats=3, divide=1, decay=0.85, reverse=0.2, seed=0):
    """The ``rpt`` module of Soundpipe (slice = one grid step repeated ``rep`` times) with the
    crossfaded slice edges of davidedemarco/GranularSynth."""
    rng = np.random.default_rng(int(seed))
    y = np.array(x, dtype=np.float64)
    L = max(32, int(float(grid) * sr))
    d = int(np.clip(divide, 1, 64))
    sub = max(16, L // d)
    w = _edge(sub, min(sub // 4, int(0.002 * sr)), y.ndim)
    i = 0
    while i + L <= len(y):
        if rng.random() >= float(chance):
            i += L
            continue
        unit = np.array(x[i:i + sub], dtype=np.float64)
        if rng.random() < float(reverse):
            unit = unit[::-1]
        unit = np.concatenate([unit * w] * d)[:L]
        for k in range(max(1, int(repeats))):
            j = i + k * L
            if j + len(unit) > len(y):
                break
            y[j:j + len(unit)] = unit * float(decay) ** k
        i += max(1, int(repeats)) * L
    return y


@effect("paulstretch", "Extreme time-stretch that turns any sound into a slowly evolving wash (random-phase windows), or holds one instant as an endless pad.",
        stretch=(8.0, "length ratio, 1..1000"), window=(0.25, "seconds: longer = smoother and more blurred in time"),
        hold=(-1.0, "seconds: freeze the sound at this instant instead of stretching (-1 = off)"),
        length=(4.0, "seconds of output when `hold` is used"), smear=(0.0, "0..1 blur across frequency (a held note becomes a noise band)"),
        seed=(0, "phase seed"))
def paulstretch(x, sr=DEFAULT_SR, stretch=8.0, window=0.25, hold=-1.0, length=4.0, smear=0.0, seed=0):
    """Nasca's algorithm (as in Soundpipe ``paulstretch.c``): windows of the input taken every
    (W / 2) / stretch samples, each resynthesised with its magnitudes and uniformly random phases,
    overlap-added at W / 2, then the amplitude ripple of the overlap is divided out with
    h - (1 - h) cos(2 pi i / (W / 2)), h = (1 + sqrt(0.5)) / 2. The window is Nasca's
    (1 - x^2)^1.25. ``hold`` and ``smear`` are the snapshot freeze of arraypress/paulstretch
    (freeze.js: one window, a box blur over max(1, 50 smear) bins, fresh phases every hop)."""
    rng = np.random.default_rng(int(seed))
    n = x.shape[0]
    W = max(64, int(float(window) * sr) // 2 * 2)
    half = W // 2
    win = (1.0 - np.linspace(-1.0, 1.0, W) ** 2) ** 1.25
    st = float(np.clip(stretch, 1.0, 1000.0))
    n_out = int(float(length) * sr) if hold >= 0 else int(n * st)
    frames = n_out // half + 1
    starts = np.full(frames, float(hold) * sr) if hold >= 0 else np.arange(frames) * half / st
    starts = np.clip(starts, 0, max(n - 1, 0)).astype(int)
    h = (1.0 + math.sqrt(0.5)) * 0.5
    ripple = np.tile(h - (1.0 - h) * np.cos(2 * np.pi * np.arange(half) / half), frames)
    blur = 2 * max(1, int(float(smear) * 50)) + 1 if smear > 0.01 else 0

    def one(s):
        sp = np.concatenate([s, np.zeros(W)])
        out = np.zeros(frames * half + W)
        for i, a in enumerate(starts):
            mag = np.abs(np.fft.rfft(sp[a:a + W] * win))
            if blur:
                mag = uniform_filter1d(mag, blur)
            out[i * half:i * half + W] += np.fft.irfft(mag * np.exp(1j * rng.uniform(0, 2 * np.pi, len(mag))), W) * win
        out[:frames * half] *= ripple
        return out[half:half + n_out]

    y = _per_channel(one, np.asarray(x, float))
    rms = lambda a: math.sqrt(float(np.mean(np.square(a)))) + 1e-12
    return y * min(rms(x) / rms(y), float(np.max(np.abs(x))) / (float(np.max(np.abs(y))) + 1e-12))   # never louder than the input


@effect("waveset", "Waveset repetition: each cycle between zero crossings is played several times and the next ones skipped. Buzzy, pitch drops by octaves, speech turns to insect chatter.",
        repeats=(2, "times each kept cycle is played (2 = an octave down in feel, 4 = two)"), keep_length=(True, "false = keep every cycle, so the sound gets `repeats` times longer"))
def waveset(x, sr=DEFAULT_SR, repeats=2, keep_length=True):
    """Soundpipe ``waveset.c`` (Wishart's waveset distortion)."""
    m = to_mono(np.asarray(x, float))
    zc = np.flatnonzero((m[:-1] < 0) & (m[1:] >= 0)) + 1
    r = max(1, int(repeats))
    if len(zc) < 3 or r == 1:
        return x
    sets = [x[a:b] for a, b in zip(zc[:-1], zc[1:])]
    y = np.concatenate([x[:zc[0]]] + [s for ws in (sets[::r] if keep_length else sets) for s in [ws] * r] + [x[zc[-1]:]])
    return pad_to(y, len(x))[:len(x)] if keep_length else y


@effect("formant_shift", "Move the formants without changing the pitch: a bigger or smaller speaker, the same notes.",
        semitones=(-3.0, "+ smaller / brighter, - bigger / darker (-12..12)"))
def formant_shift(x, sr=DEFAULT_SR, semitones=-3.0):
    x = np.asarray(x, float)
    return S.transfer_envelope(x, x, sr, shift=float(np.clip(semitones, -24.0, 24.0)))


@effect("cyber_voice", "Synthetic / augmented voice in one step: formant shift, vocoder, ring modulation, a lossy link and a radio band. For speech layers and recorded voices.",
        formant=(-3.0, "semitones the formants move (- = larger, colder)"), pitch=(110.0, "vocoder carrier: Hz or a note name"),
        vocode=(0.6, "0 natural .. 1 fully vocoded"), ring=(70.0, "ring modulator Hz (30..180)"), ring_mix=(0.25, "0..1"),
        loss=(0.06, "fraction of 30 ms packets lost (0 = clean link)"), conceal=("noise", "mute | repeat | noise: what a lost packet becomes"),
        radio=(1.0, "0 full band .. 1 the 300-3400 Hz band of a comms channel"), seed=(0, "variation"))
def cyber_voice(x, sr=DEFAULT_SR, formant=-3.0, pitch=110.0, vocode=0.6, ring=70.0, ring_mix=0.25, loss=0.06,
                conceal="noise", radio=1.0, seed=0):
    rms = lambda a: math.sqrt(float(np.mean(np.square(a)))) + 1e-12
    y = formant_shift(x, sr, formant) if formant else np.asarray(x, float)
    if vocode > 0:
        v = FX["vocoder"]["fn"](y, sr, carrier="saw", freq=pitch, bands=16, hiss=0.12, seed=int(seed))
        y = y * (1.0 - float(vocode)) + v * (float(vocode) * rms(y) / rms(v))
    if ring_mix > 0:
        y = FX["ringmod"]["fn"](y, sr, freq=float(ring), mix=float(ring_mix))
    if loss > 0:
        y = packet_loss(y, sr, loss=loss, burst=2.0, packet_ms=30.0, conceal=conceal, seed=seed)
    if radio > 0:
        pk = float(np.max(np.abs(y))) + 1e-12
        y = y * (1.0 - float(radio)) + float(radio) * pk * FX["telephone"]["fn"](y / pk, sr, drive=2.0)
    return y * min(rms(x) / rms(y), 0.99 / (float(np.max(np.abs(y))) + 1e-12))   # the input's level, never clipping


# =============================================================================================
# STATISTICAL TEXTURES
# =============================================================================================
# McDermott & Simoncelli, "Sound texture perception via statistics of the auditory periphery",
# Neuron 71, 2011 (Experimental Procedures): 30 half-cosine filters equally spaced on the ERB scale
# from 52 to 8844 Hz plus a low and a high end filter (squared responses sum to one), Hilbert
# envelopes compressed with the exponent 0.3 and sampled at 400 Hz, statistics of those envelopes,
# imposed on noise by iteration while each band keeps its own fine structure.
# ponytail: a reduced statistic set. Kept: the envelope marginals (as 64 quantiles, which carry the
# paper's mean, variance, skew and kurtosis), the full band-to-band envelope correlation, and the
# modulation power in 9 octave bands from 0.5 Hz. Dropped: the C1 and C2 modulation correlations, so
# sharp asymmetric onsets (fire crackle, applause) come out softer. Imposed by projection (Cholesky
# recolouring, band rescaling, rank matching) instead of the paper's conjugate-gradient search.

TEX_BANDS, TEX_ENV_SR, TEX_POW, TEX_Q = 30, 400.0, 0.3, 64
_TEX_MOD = 0.5 * 2.0 ** np.arange(10)                        # modulation band edges, Hz


def _erb(f):
    return 21.4 * np.log10(1.0 + 0.00437 * np.asarray(f, float))


def _tex_len(n: int) -> int:
    while sfft.next_fast_len(n) != n:
        n -= 1
    return n


def _tex_bank(n: int, sr: int) -> np.ndarray:
    e = _erb(np.fft.rfftfreq(n, 1.0 / sr))
    c = np.linspace(_erb(52.0), _erb(min(8844.0, 0.45 * sr)), TEX_BANDS + 2)
    H = np.cos(np.clip((e[None, :] - c[:, None]) / (c[1] - c[0]), -1.0, 1.0) * np.pi / 2)
    H[0, e < c[0]] = 1.0
    H[-1, e > c[-1]] = 1.0
    return H


def _tex_envelopes(x: np.ndarray, H: np.ndarray, m: int):
    """Compressed envelopes at the envelope rate (bands, m) and the phase of each band's fine structure."""
    n = len(x)
    X = sfft.rfft(x)
    env, ph = np.empty((len(H), m)), np.empty((len(H), n), np.float32)
    Z = np.zeros(n, complex)
    for k, h in enumerate(H):
        Z[:len(X)] = 2.0 * X * h
        a = sfft.ifft(Z)
        ph[k] = np.angle(a)
        env[k] = resample(np.abs(a) ** TEX_POW, m)
    return env, ph


def _tex_masks(m: int):
    fm = np.fft.rfftfreq(m, 1.0 / TEX_ENV_SR)
    return [(fm >= lo) & (fm < hi) for lo, hi in zip(_TEX_MOD[:-1], _TEX_MOD[1:])]


def texture_stats(x: np.ndarray, sr: int = DEFAULT_SR) -> dict:
    """Envelope statistics of a recording (at least a second or two of a steady texture)."""
    x = to_mono(np.asarray(x, float))
    n = _tex_len(len(x))
    m = int(n * TEX_ENV_SR / sr)
    env, _ = _tex_envelopes(x[:n], _tex_bank(n, sr), m)
    P = np.abs(np.fft.rfft(env - env.mean(axis=1, keepdims=True), axis=1)) ** 2
    mod = np.stack([P[:, k].sum(axis=1) for k in _tex_masks(m)], axis=1) / (P[:, 1:].sum(axis=1, keepdims=True) + 1e-30)
    return {"sr": int(sr), "quantiles": np.quantile(env, np.linspace(0, 1, TEX_Q), axis=1).T, "modulation": mod,
            "corr": np.corrcoef(env)}


def texture_synth(stats: dict, dur: float, seed: int = 0, iters: int = 12) -> np.ndarray:
    """A new texture of any length with the statistics of ``texture_stats``, at ``stats['sr']``. The
    filters are circular, so the result loops without a seam.
    # ponytail: 32 float32 phase tracks in memory (6 MB per second at 48 kHz): capped at 60 s; loop it."""
    sr = stats["sr"]
    n = _tex_len(int(float(np.clip(dur, 0.5, 60.0)) * sr))
    m = int(n * TEX_ENV_SR / sr)
    H = _tex_bank(n, sr)
    B = len(H)
    q, grid = stats["quantiles"], np.linspace(0, 1, TEX_Q)
    eye = 1e-3 * np.eye(B)
    Lt = np.linalg.cholesky(stats["corr"] + eye)
    masks = _tex_masks(m)
    x = np.random.default_rng(int(seed)).standard_normal(n)
    for _ in range(max(1, int(iters))):
        env, ph = _tex_envelopes(x, H, m)
        z = env - env.mean(axis=1, keepdims=True)
        z /= z.std(axis=1, keepdims=True) + 1e-12
        z = Lt @ np.linalg.solve(np.linalg.cholesky(np.corrcoef(z) + eye), z)
        Zf = np.fft.rfft(z, axis=1)
        P = np.abs(Zf) ** 2
        tot = P[:, 1:].sum(axis=1)
        for j, k in enumerate(masks):
            Zf[:, k] *= np.sqrt(stats["modulation"][:, j] * tot / (P[:, k].sum(axis=1) + 1e-30))[:, None]
        z = np.fft.irfft(Zf, m, axis=1)
        X = np.zeros(n // 2 + 1, complex)
        for b in range(B):
            rank = np.argsort(np.argsort(z[b])) / (m - 1.0)
            e = np.maximum(resample(np.interp(rank, grid, q[b]), n), 0.0) ** (1.0 / TEX_POW)
            X += sfft.rfft(e * np.cos(ph[b])) * H[b]
        x = sfft.irfft(X, n)
    return x


@effect("texturize", "Turn a recording of a steady texture (rain, a server room, a crowd, static) into a new, endless, seamlessly looping one of any length with the same character.",
        length=(8.0, "seconds of output, up to 60"), iters=(12, "refinement passes (more = closer, slower)"), seed=(0, "a different rendition"))
def texturize(x, sr=DEFAULT_SR, length=8.0, iters=12, seed=0):
    if x.shape[0] < sr // 2:
        return x
    return texture_synth(texture_stats(x, sr), length, seed, iters)
