"""Generates the reference docs from the code, so they cannot drift from it.

    uv run python examples/build_docs.py

Writes docs/catalog.md (every instrument, drum, sfx, effect and layer type with its parameters: what
JSON specs and the CLI accept) and docs/api.md (the Python API: every public class and function of every
module, with its signature and docstring).
"""
from __future__ import annotations

import importlib
import inspect
import pkgutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import genny  # noqa: E402
from genny import drums as D, fx as FX, instruments as I, sfx as S, spec as SP  # noqa: E402

DOCS = ROOT / "docs"


def module_of(fn) -> str:
    return (inspect.getmodule(fn).__name__ if inspect.getmodule(fn) else "?").replace("genny.", "")


def params_table(params: dict) -> list[str]:
    if not params:
        return []
    rows = ["", "| param | default | meaning |", "|---|---|---|"]
    for name, (default, text) in params.items():
        rows.append(f"| `{name}` | `{default!r}` | {str(text).replace('|', '/')} |")
    return rows + [""]


def catalog() -> str:
    out = ["# genny catalog", "",
           "Generated by `examples/build_docs.py` from the registries; `genny list --json` prints the same data.",
           "Use these names in JSON specs (`\"inst\"`, `\"kind\"`, fx `\"type\"`, layer `\"type\"`) and on the command line.", ""]
    sections = [
        ("Instruments", I.REGISTRY, '{"type": "seq", "inst": "<name>", "steps": "C4:1 E4:1", "params": {...}}'),
        ("Drums", D.REGISTRY, '{"type": "drum", "kind": "<name>", "params": {...}}  or a "pattern" layer'),
        ("Sound effects", S.REGISTRY, '{"type": "sfx", "kind": "<name>", "params": {...}}'),
        ("Effects", FX.REGISTRY, '"fx": [{"type": "<name>", ...params}]  on a layer, a group or the whole spec'),
    ]
    out += ["| section | count |", "|---|---|"] + [f"| {t} | {len(r)} |" for t, r, _ in sections]
    out += [f"| Extra layer types | {len(SP.LAYER_TYPES)} |", ""]
    for title, reg, usage in sections:
        out += [f"## {title} ({len(reg)})", "", f"Usage: `{usage}`", ""]
        by_module: dict[str, list[str]] = {}
        for name, e in reg.items():
            by_module.setdefault(module_of(e["fn"]), []).append(name)
        out += ["Index by module: " + "; ".join(f"**{m}**: " + ", ".join(f"`{n}`" for n in names)
                                                for m, names in sorted(by_module.items())), ""]
        for name, e in sorted(reg.items()):
            tag = f" — {e['family']}, range {e['range']}" if "range" in e else ""
            out += [f"### `{name}`{tag}", "", f"{e['desc']}  *(module `{module_of(e['fn'])}`)*"]
            out += params_table(e["params"]) or [""]
    out += [f"## Extra layer types ({len(SP.LAYER_TYPES)})", "",
            "Built-in: `synth`, `seq`, `drum`, `pattern`, `sfx`, `speech`, `file`, `silence`, `group` (see AGENTS.md).", ""]
    for name, fn in sorted(SP.LAYER_TYPES.items()):
        out += [f"**{name}** — {SP.LAYER_HELP.get(name, '')}", ""]
        out += [f"### `{name}`  *(module `{module_of(fn)}`)*", "", inspect.getdoc(fn) or "", ""]
    return "\n".join(out) + "\n"


def api() -> str:
    out = ["# genny Python API", "",
           "Generated by `examples/build_docs.py`. Every public class and function, by module. Names starting",
           "with `_` are private. Top-level `import genny` re-exports: " + ", ".join(f"`{n}`" for n in sorted(genny.__all__)) + ".", ""]
    names = sorted(m.name for m in pkgutil.walk_packages(genny.__path__, "genny."))
    for modname in names:
        if modname.rsplit(".", 1)[-1].startswith("_"):
            continue
        mod = importlib.import_module(modname)
        items = [(n, o) for n, o in vars(mod).items()
                 if not n.startswith("_") and (inspect.isclass(o) or inspect.isfunction(o)) and getattr(o, "__module__", None) == modname]
        if not items:
            continue
        out += [f"## `{modname}`", "", (inspect.getdoc(mod) or "").strip(), ""]
        for n, o in items:
            try:
                sig = str(inspect.signature(o))
            except (TypeError, ValueError):
                sig = "(...)"
            doc = (inspect.getdoc(o) or "").strip()
            if inspect.isclass(o) and doc.startswith(f"{n}("):   # dataclass auto-doc is just the signature again
                doc = ""
            out += [f"### `{n}{sig}`", "", doc, ""]
            if inspect.isclass(o):
                for mn, mo in vars(o).items():
                    if mn.startswith("_") or not (inspect.isfunction(mo) or isinstance(mo, property)):
                        continue
                    f = mo.fget if isinstance(mo, property) else mo
                    msig = "" if isinstance(mo, property) else str(inspect.signature(f))
                    first = (inspect.getdoc(f) or "").strip().split("\n\n")[0].replace("\n", " ")
                    out.append(f"- `.{mn}{msig}`" + (f" — {first}" if first else ""))
                out.append("")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    DOCS.mkdir(exist_ok=True)
    for name, text in (("catalog.md", catalog()), ("api.md", api())):
        (DOCS / name).write_text(text, encoding="utf-8")
        print(f"wrote docs/{name} ({len(text.splitlines())} lines)")
