"""Level-matches the instruments: measures each one in the middle of its register and writes the
trims to genny/_levels.py, so that equal `gain` means about equally loud whatever the instrument.

Run after adding or re-voicing an instrument:   uv run python examples/level_match.py
Add --check to only print how far each instrument is from the target (no file is written).
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from genny import instruments as I  # noqa: E402
from genny.analysis import loudness  # noqa: E402
from genny.notes import midi_to_freq, note_to_midi  # noqa: E402

TARGET = -12.0   # K-weighted dB of the loudest 150 ms: about what a kick or snare measures at gain 1
SR = 44100


def measure(name: str) -> float:
    lo, hi = I.REGISTRY[name]["range"].split("-")
    lo, hi = note_to_midi(lo), note_to_midi(hi)
    levels = []
    for m in (lo + (hi - lo) // 4, (lo + hi) // 2, hi - (hi - lo) // 4):   # three notes across the register
        y = I.REGISTRY[name]["fn"](midi_to_freq(m), 0.5, SR, 0.9) * I.key_gain(midi_to_freq(m))
        levels.append(loudness(y, SR, window=0.15))
    return sum(levels) / len(levels)


def main():
    check = "--check" in sys.argv
    trims = {}
    for name in I.REGISTRY:
        level = measure(name)
        trims[name] = round(10 ** ((TARGET - level) / 20), 3)
        if check:
            now = level + 20 * __import__("math").log10(I.TRIM.get(name, 1.0))
            print(f"{name:<16} {now:6.1f} dB  ({now - TARGET:+.1f})")
    if check:
        return
    body = ",\n".join(f'    "{k}": {v}' for k, v in trims.items())
    (ROOT / "genny" / "_levels.py").write_text(
        '"""Level-matching trims for instruments (generated by examples/level_match.py; do not edit by hand).\n\n'
        "Each instrument is scaled so that notes across its register at vel 0.9 measure the same K-weighted\n"
        'loudness, so `gain` means the same thing whatever the instrument.\n"""\n'
        f"TRIM: dict[str, float] = {{\n{body},\n}}\n", encoding="utf-8")
    print(f"wrote {len(trims)} trims to genny/_levels.py")


if __name__ == "__main__":
    main()
